apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ${{values.deployName}}
  namespace: ${{values.namespace}}
spec:
  replicas: ${{values.replicas}}
  selector:
    matchLabels:
      app: ${{values.deployName}}
  template:
    metadata:
      labels:
        app: ${{values.deployName}}
    spec:
      containers:  
        - name: ${{values.deployName}}
          image: ${{values.imageName}}
          imagePullPolicy: ${{values.pullPolicy}}
          ports:
            - containerPort: ${{values.containerPort}}
