app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: http://localhost:7007
  title: Scaffolded Backstage App
  extensions:
  - entity-content:kubernetes/kubernetes:
      config:
        filter: kind:component,api,resource,system

organization:
  name: My Backstage

kubernetes:
  frontend:
      podDelete:
        enabled: true
  serviceLocatorMethod:
    type: 'singleTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${K8S_URL}
          name: local
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          # serviceAccountToken: ${K8S_MINIKUBE_TOKEN}
          # dashboardUrl: http://127.0.0.1:64713 # url copied from running the command: minikube service kubernetes-dashboard -n kubernetes-dashboard
          # dashboardApp: standard
          caData: ${K8S_CONFIG_CA_DATA}
          # caFile: '' # local path to CA file
          # customResources:
          #   - group: 'argoproj.io'
          #     apiVersion: 'v1alpha1'
          #     plural: 'rollouts'
integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: ${GITHUB_TOKEN}

proxy:
  endpoints:
    '/argocd/api':
      target: ${ARGOCD_SERVER_URL_PROXY}
      changeOrigin: true
      secure: false
      headers:
        Cookie: 
          ${ARGOCD_TOKEN}

    '/prometheus/api':
      target: ${PROMETHEUS_URL_PROXY}
      credentials: dangerously-allow-unauthenticated
    '/jira/api':
      target: ${JIRA_URL}
      headers:
        Authorization: ${JIRA_TOKEN_MINE}
        Content-Type: 'application/json'
        Accept: 'application/json'
        X-Atlassian-Token: 'nocheck'
        User-Agent: 'JIRA'
    '/grafana/api':
      target: ${GRAFANA_URL}
      headers:
        Authorization: Bearer ${GRAFANA_SA_TOKEN}

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: http://localhost:7007
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':7007'

  # config options: https://node-postgres.com/apis/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src:
      - ${JIRA_URL}
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  
  reading:
    allow:
      - host: 'demo.backstage.io'
        paths:
          - /api/graphql/schema


techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.


auth:
  providers:
    development:
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          signIn:
            resolvers:
              - resolver: usernameMatchingUserEntityName
    guest: {}



catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]
  locations:
    # Local example data, replace this with your production config, these are intended for demo use only.
    # File locations are relative to the backend process, typically in a deployed context, such as in a Docker container, this will be the root
    - type: file
      target: ./examples/entities.yaml

    # Local example template
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]

    - type: file
      target: ./examples/other-entities.yaml
      
    - type: file
      target: ./examples/slack-notifications.yaml
      rules:
        - allow: [Template]

    - type: url
      target: https://github.com/mclarke47/dice-roller/blob/master/catalog-info.yaml
    
    - type: file
      target: ./examples/template/template-deploy.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./examples/argocd.yaml
      rules:
        - allow: [Template]

  useUrlReadersSearch: true



permission:
  # setting this to `false` will disable permissions
  enabled: true

notifications:
  processors:
    slack:
      - token: ${SLACK_TOKEN}

slack:
  token: ${SLACK_TOKEN}
  webhookUrl: ${WEBHOOK_URL}
  conversationId: C092B8YEPT6
  conversationName: mine

argocd:
  username: ${ARGOCD_USERNAME}
  password: ${ARGOCD_PASSWORD}
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: argocd-server
          secure: false
          url: ${ARGOCD_SERVER_URL}
          token: ${ARGOCD_AUTH_TOKEN}

ai:
  #(Optional) Supported sources to query information from using RAG. This can be used to omit unnecessary sources from being retrievable. Defaults to [catalog]
  supportedSources: ['catalog','techdocs','api']
  prompts:
    # (Optional) Prefix prompt to add to the query. This prompt is always succeeded by a text blob of embeddings retrieved by the RAG engine.
    prefix: 'you are an LLM designed to do this and that... based on... Use the following documents to...'

    # Suffix prompt to add to the query. This prompt is always succeeded by text query user has input.
    suffix: 'Begin! \n Question: \n'
  storage:
    pgvector:
      # (Optional) The size of the chunk to flush when storing embeddings to the DB. Defaults to 500
      chunksize: 500

  # Embeddings engine configuration options
  embeddings:
    # Generic embeddings options
    # (Optional) The chunk size of an embedding. Determines how big or small the individual pieces of context stored alongside the vectors and sent to the LLM are. Defaults to 1000
    chunkSize: 1000

    # (Optional) The overlap between adjacent chunks of embeddings. The bigger the number, the more overlap. Defaults to 200
    chunkOverlap: 200
    concurrencyLimit: 10
    openai:
      # baseURL: 'https://generativelanguage.googleapis.com/v1beta/'
      modelName: 'text-embedding-3-small'
      batchSize: 512
      embeddingsDimensions: 1536
      # apiKey: 'AIzaSyBt9_oD7eeKd46xKOmetEjUZbYZLzmSNGU'
      openAIApiKey: ${OPENAI_API_KEY}
grafana: 
  domain: ${GRAFANA_URL}