apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    'backstage.io/kubernetes-id': dice-roller
    'backstage.io/kubernetes-namespace': default
    'backstage.io/kubernetes-cluster': cluster.local

  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: justinmihigo
  lifecycle: experimental
