apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    'backstage.io/kubernetes-id': backstage
    'backstage.io/kubernetes-namespace': backstage
    'backstage.io/kubernetes-cluster': local
    github.com/project-slug: justinmihigo/backstage
    backstage.io/managed-by-location: url:https://github.com/justinmihigo/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: justinmihigo
  lifecycle: experimental
