services:
  app:
    image: justinmihigo/backstage:2.0.6
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT:  5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backstage_plugin_app
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      K8S_URL: ${K8S_URL}
      K8S_CONFIG_CA_DATA: ${K8S_CONFIG_CA_DATA}
      WEBHOOK_URL: ${WEBHOOK_URL}
      SLACK_TOKEN: ${SLACK_TOKEN}
      ARGOCD_TOKEN: ${ARGOCD_TOKEN}
      ARGOCD_USERNAME: ${ARGOCD_USERNAME}
      ARGOCD_SERVER_URL_PROXY: ${ARGOCD_SERVER_URL_PROXY}
      ARGOCD_PASSWORD: ${ARGOCD_PASSWORD}
      PROMETHEUS_URL_PROXY: ${PROMETHEUS_URL_PROXY}
      ARGOCD_AUTH_TOKEN: ${ARGOCD_AUTH_TOKEN}
      POD_NAMESPACE: ${POD_NAMESPACE}
      ARGOCD_SERVER_URL: ${ARGOCD_SERVER_URL}
      PROMETHEUS_TOKEN: ${PROMETHEUS_TOKEN}
      K8S_SERVICE_ACCOUNT_TOKEN: ${K8S_SERVICE_ACCOUNT_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JIRA_TOKEN: ${JIRA_TOKEN}
      JIRA_TOKEN_BEARER: ${JIRA_TOKEN_BEARER}
      JIRA_TOKEN_PLAIN: ${JIRA_TOKEN_PLAIN}
      JIRA_TOKEN_MINE: ${JIRA_TOKEN_MINE}
      GRAFANA_SA_TOKEN: ${GRAFANA_SA_TOKEN}
      GRAFANA_URL: http://localhost:3001
      JIRA_URL: https://mihigojustin.atlassian.net/
    depends_on:
      - database
    ports:
      - "7007:7007"
  database:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backstage_plugin_app
    ports:
      - "5432:5432"
