services:
  app:
    image: justinmihigo/backstage:2.0.5
    ports: 
      - "7007:7007"
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backstage
    ports:
      - "5432:5432"
