apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: infra
spec:
  owner: user:justinmihigo
  
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-web
  description: A sample web
  annotations:
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: nginx-server-1
    prometheus.io/rule: 'sum by (pod) (rate(container_cpu_usage_seconds_total{namespace="default"}[5m]))'
    prometheus.io/alert: all
    backstage.io/source-location: url:https://github.com/justinmihigo/backstage
    backstage.io/managed-by-location: url:https://github.com/justinmihigo/backstage
    github.com/project-slug: justinmihigo/backstage
  links:
    - url: https://github.com/justinmihigo/backstage
      title: Project Repository
      icon: github
  tags:
    - service
spec:
  type: website
  lifecycle: experimental
  owner: user:justinmihigo
  system: infra
  consumesApis:
    - graphql-example

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: graphql-example
  description: GraphQL Backend plugin
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/techdocs-builder: local
spec:
  owner: user:justinmihigo
  type: graphql
  lifecycle: experimental
  system: infra
  apiConsumedBy:
    - node-web
  definition: 
    $text: https://demo.backstage.io/api/graphql/schema

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  title: Pet Store API
  description: The main API for managing pets in the system.

spec:
  type: openapi
  lifecycle: production
  owner: group:default/guests
  system: infra # Optional: If it belongs to a larger system
  definition: |
    openapi: 3.0.0
    info:
      title: Simple Pet Store API
      version: 1.0.0
      description: A tiny API for managing pets.
    servers:
      - url: https://api.petstore.example.com/v1
        description: Production server
      - url: http://localhost:8080/v1
        description: Local development server
    paths:
      /pets:
        get:
          summary: List all pets
          operationId: listPets
          tags:
            - pets
          responses:
            '200':
              description: A list of pets.
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Error'
    components:
      schemas:
        Pet:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
