apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/techdocs-ref: url:${{values.repoUrl}}
    backstage.io/managed-by-location: url:${{values.repoUrl}}
    github.com/project-slug: justinmihigo/${{values.repoName}}
spec:
  type: service
  owner: user:justinmihigo
  lifecycle: experimental
