site_name: ${{values.name | dump}}
site_description: 'Main documentation for Backstage features and framework APIs'
# repo_url: ${{values.repoUrl}}
# edit_uri: edit/main/docs
# nav:
#   - Home: index.md
plugins:
  - techdocs-core